version: '3.9'
services:
    registry:
        image: registry:2
        ports:
            - 5000:5000
        restart: always
        volumes:
          - docker-registry-data:/var/lib/registry
    docker-registry-ui:
        image: parabuzzle/craneoperator:latest
        ports:
        - "8086:80"
        environment:
        - REGISTRY_HOST=registry
        - REGISTRY_PORT=5000
        - REGISTRY_PROTOCOL=http
        - SSL_VERIFY=false
        - USERNAME=admin
        - PASSWORD=123
        restart: always
        depends_on:
        - registry
volumes:
    docker-registry-data: {}